### ISSUE TITLE
parser repeated has something wrong in proto3

### ISSUE THREAD

**Issue by langyanduan** [alexeyxo/protobuf-swift#138]
##### protoc
```
$ brew update
$ brew install protobuf --devel --verbose
...
$ protoc --version
libprotoc 3.0.0
```

##### protobuf-swift
```
$ git clone https://github.com/alexeyxo/protobuf-swift
$ git checkout -b ProtoBuf3.0-Swift2.0 origin/ProtoBuf3.0-Swift2.0
$ ./scripts/build.sh
```

##### Cocoapods
```
pod 'ProtocolBuffers-Swift', :git => 'https://github.com/alexeyxo/protobuf-swift', :branch => 'ProtoBuf3.0-Swift2.0'
```

---

##### protobuf define
```
syntax = "proto3";

package Test;
option java_multiple_files  = false;
option java_outer_classname = "TestProto";
option java_package         = "com.test.protobuf";
option csharp_namespace     = "Test.Protobuf";
option objc_class_prefix    = "PBM";

message Home {
    repeated bool door = 1;
}
```

##### swift parser
```swift
do {
    let homeBuilder = Test.Home.getBuilder()
    homeBuilder.setDoor([true, false, true, false])
    let home = try homeBuilder.build()
    let homeData = home.data()
    let home2 = try Test.Home.parseFromData(homeData)
    
    print("home:\(home)")
    print("home2: \(home2)")

} catch {
    print("catch \(error)")
}
```

###### output

```
home: door[0]: true
 door[1]: false
 door[2]: true
 door[3]: false

home2: 1: 1
1: 0
1: 1
1: 0
```

![Debugger](http://i.imgur.com/9mI6dqm.png?1)

**Comment by alexeyxo** [comment]
Done. Thanks.

**Comment by langyanduan** [comment]
it seems still has some problem. 
the message generate by swift is different with other languge (like C#, Java and Objective-C)

### proto
```
syntax = "proto3";

package Test;
option java_multiple_files  = false;
option java_outer_classname = "TestProto";
option java_package         = "com.test.protobuf";
option csharp_namespace     = "Test.Protobuf";
option objc_class_prefix    = "PBM";

message Home {
    int32 window       = 1;
    repeated bool door = 2;
}
```


### swift
```swift
let builder = Test.Home.getBuilder()
builder.setWindow(123)
builder.setDoor([false, true, false, true, true, true])
let data = try? builder.build().data()
```

output
```
Printing description of data:
▿ Optional<NSData>
  - Some : <087b1000 10011000 10011001 1001>
```


### objc 
```objective-c
const BOOL doors[] = { false, true, false, true, true, true, };
PBMHome *home = [PBMHome message];
home.window = 123;
home.doorArray = [[GPBBoolArray alloc] initWithValues:doors count:sizeof(doors) / sizeof(BOOL)];
NSData* data = home.data;
```
output
```
Printing description of data:
<087b1206 00010001 0101>
```

### **C#**
```csharp
Test.Protobuf.Home home = new Test.Protobuf.Home();
home.Window = 123;
home.Door.Add(new bool[] { false, true, false, true, true, true });
var bytes = home.ToByteArray();
```

output
```
-       bytes   {byte[0x0000000a]}  byte[]
        [0] 0x08    byte
        [1] 0x7b    byte
        [2] 0x12    byte
        [3] 0x06    byte
        [4] 0x00    byte
        [5] 0x01    byte
        [6] 0x00    byte
        [7] 0x01    byte
        [8] 0x01    byte
        [9] 0x01    byte
```


### java
```java
TestProto.Home.Builder home = TestProto.Home.newBuilder();
home.setWindow(123);
home.addDoor(false);
home.addDoor(true);
home.addDoor(false);
home.addDoor(true);
home.addDoor(true);
home.addDoor(true);
byte[] arr = home.build().toByteArray();
```

output
```
0x08 0x7b 0x12 0x06 0x00 0x01 0x00 0x01 0x01 0x01
```

**Comment by caseymrm** [comment]
Hi @alexeyxo, thanks for your hard work here. I am still seeing byte differences with repeated strings, perhaps related to proto3 repeated fields always being packed:

.proto:
```
message Test {
  repeated string test = 1;
}
```

Swift:
```
    try! print("Swift: ", Handlers.Test.Builder().setTest(["hello"]).build().data())
```
output
```
Swift:  <0a060568 656c6c6f>
```

Go:
```
		data, _ := (&pb.Test{Test: []string{"hello"}}).Marshal()
                log.Printf("Go: %x\n", data)
```
output
```
Go: 0a0568656c6c6f
```

**Comment by nstublen** [comment]
I'll echo caseymrm's thanks on this one.

I'm seeing what is surely a related issue, but we're using version 2.4.3 with Swift 2.2 (so Proto2/Swift 2).  We're repeated an enumeration data type.

I brought this code onto the master branch from your most recent patch for this issue:

swift_message.cc:

>             // Drop the SYNTAX_PROTO3 check...
>            if (field->options().packed() || field->is_repeated()) {
>                tag = WireFormatLite::MakeTag(field->number(),
>                                              WireFormatLite::WIRETYPE_LENGTH_DELIMITED);
>            }

Your patch also updated swift_enum_field.cc to on several `descriptor_->options().packed()` checks.  I modified the code to always execute the code in those `if` blocks.

This generated code that seems to correctly decode the repeated enumeration, but I have no idea if it may break something else.

Any chance you'd be able to provide some guidance on the appropriate fix here?

**Comment by alexeyxo** [comment]
You can test

**Comment by caseymrm** [comment]
Hi @alexeyxo, I am still seeing a difference:

```
message Test {
  repeated string test = 1;
}
```

Swift:
```
    try! print("Swift: ", Handlers.Test.Builder().setTest(["hello"]).build().data())

Swift:  <0a060568 656c6c6f>
```

Go:
```
                data, _ := (&pb.Test{Test: []string{"hello"}}).Marshal()
                log.Printf("Go: %x\n", data)

Go: 0a0568656c6c6f
```

**Comment by alexeyxo** [comment]
From last commit:
```protobuf
syntax = "proto3";
message Test {
  repeated string test = 1;
}
```

```
Swift:  <0a056865 6c6c6f>
```

**Comment by caseymrm** [comment]
Awesome, you're right, sorry, I got my Swift2 and Swift3 branches crossed. Thank you!
