### ISSUE TITLE
Swift 2.0 support

### ISSUE THREAD

**Issue by alexeyxo** [alexeyxo/protobuf-swift#69]

**Comment by thekarladam** [comment]
Is this still in progress?

**Comment by alexeyxo** [comment]
Currently in a progress.

**Comment by vyshane** [comment]
@alexeyxo, what's the state of the [2.0 branch](https://github.com/alexeyxo/protobuf-swift/tree/2.0)? Is it worth checking out for the Swift 2.0 compatibility?

**Comment by alexeyxo** [comment]
The support of the Swift 2.0 will be in few days.
2.0 branch is just a new version of compiletor and have nothing with Swift
2.0.
среда, 8 июля 2015 г. пользователь Vy-Shane написал:

> @alexeyxo <https://github.com/alexeyxo>, what's the state of the 2.0
> branch <https://github.com/alexeyxo/protobuf-swift/tree/2.0>? Is it worth
> checking out for the Swift 2.0 compatibility?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alexeyxo/protobuf-swift/issues/69#issuecomment-119393698>
> .
>


-- 
Best Regards.
Alexey Khokhlov

   - ru.linkedin.com/pub/alexey-khokhlov/35/59b/239/
   <https://ru.linkedin.com/pub/alexey-khokhlov/b3/64b/aa2>

**Comment by vyshane** [comment]
@alexeyxo okay, thanks for clearing that up.

**Comment by hubert3** [comment]
So compiling with Xcode 7 beta 2 is not expected to work currently?

I'm only seeing one error, but in a lot of locations:

/Pods/ProtocolBuffers-Swift/src/ProtocolBuffers/runtime-pb-swift/GoogleProtobuf_Descriptor.pb.swift:5776:86: Redundant conformance of 'Google.Protobuf.EnumValueOptions' to protocol 'Hashable'

**Comment by alexeyxo** [comment]
Done.

**Comment by mcudich** [comment]
I just pulled this Swift 2.0 branch, and it looks like the pre-compiled messages are still not compiling. For example: https://github.com/alexeyxo/protobuf-swift/blob/Compiler2.0-ProtoBuf2.6-Swift2.0/src/ProtocolBuffers/runtime-pb-swift/Google.Protobuf.Any.proto.swift. The compiler complains at line 38, that this is a redundant conformance to Hashable. Any ideas?

**Comment by alexeyxo** [comment]
@mcudich Fixed.
